#!/bin/bash
echo "🚀 Création de la structure Flutter (lib/) pour ton projet..."

mkdir -p lib/{core/{constants,utils,services},data/{models,repositories,datasources},features/{auth/{presentation/{screens,providers},domain/repositories},dashboard/{presentation/{screens,providers}},campaigns/{presentation/{screens,providers}},sharing/{presentation/{screens,providers}},earnings/{presentation/{screens,providers}},referrals/{presentation/{screens,providers}}},presentation/{widgets/{common,campaign,earnings},themes,providers}}

touch lib/{main.dart,app.dart,firebase_options.dart,core/constants/{app_colors.dart,app_strings.dart,app_constants.dart},core/utils/{validators.dart,formatters.dart,location_utils.dart,share_utils.dart},core/services/{firebase_service.dart,location_service.dart,notification_service.dart},data/models/{user_model.dart,campaign_model.dart,click_model.dart,referral_model.dart,transaction_model.dart,payment_model.dart},data/repositories/{user_repository.dart,campaign_repository.dart,click_repository.dart,referral_repository.dart},data/datasources/{firebase_datasource.dart,local_datasource.dart},features/auth/presentation/screens/{login_screen.dart,register_screen.dart,welcome_screen.dart},features/auth/presentation/providers/auth_provider.dart,features/auth/domain/repositories/auth_repository.dart,features/dashboard/presentation/screens/{dashboard_screen.dart,home_screen.dart,profile_screen.dart},features/dashboard/presentation/providers/dashboard_provider.dart,features/campaigns/presentation/screens/{campaigns_screen.dart,campaign_details_screen.dart,create_campaign_screen.dart},features/campaigns/presentation/providers/campaign_provider.dart,features/sharing/presentation/screens/share_screen.dart,features/sharing/presentation/providers/share_provider.dart,features/earnings/presentation/screens/{earnings_screen.dart,withdrawal_screen.dart,transactions_screen.dart},features/earnings/presentation/providers/earnings_provider.dart,features/referrals/presentation/screens/referrals_screen.dart,features/referrals/presentation/providers/referral_provider.dart,presentation/widgets/common/{custom_app_bar.dart,custom_button.dart,custom_text_field.dart,loading_indicator.dart},presentation/widgets/campaign/{campaign_card.dart,campaign_list.dart},presentation/widgets/earnings/{earnings_card.dart,stats_grid.dart},presentation/themes/{app_theme.dart,text_styles.dart},presentation/providers/app_provider.dart}

echo "✅ Structure créée avec succès !"
echo "📂 Arborescence disponible dans le dossier lib/"
