// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4FP5olTC2MjpUPe8x-_6k91fjvyBs6xo',
    appId: '1:387756086923:web:1e2241c4aa3f6e53c5268e',
    messagingSenderId: '387756086923',
    projectId: 'scoutapk',
    authDomain: 'scoutapk.firebaseapp.com',
    storageBucket: 'scoutapk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtQkwJgPY-9JBpXzIdz3ugGc7qdqTp3HM',
    appId: '1:387756086923:android:e57a2c216d67f0f3c5268e',
    messagingSenderId: '387756086923',
    projectId: 'scoutapk',
    storageBucket: 'scoutapk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnp9AijV78SIdYAcZmgfog0Zqk_dJi3D8',
    appId: '1:387756086923:ios:f4bf418cbb3032b2c5268e',
    messagingSenderId: '387756086923',
    projectId: 'scoutapk',
    storageBucket: 'scoutapk.firebasestorage.app',
    iosClientId: '387756086923-m67vt1h74025a4vmqok7tph0g13vfmvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.reshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnp9AijV78SIdYAcZmgfog0Zqk_dJi3D8',
    appId: '1:387756086923:ios:f4bf418cbb3032b2c5268e',
    messagingSenderId: '387756086923',
    projectId: 'scoutapk',
    storageBucket: 'scoutapk.firebasestorage.app',
    iosClientId: '387756086923-m67vt1h74025a4vmqok7tph0g13vfmvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.reshare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4FP5olTC2MjpUPe8x-_6k91fjvyBs6xo',
    appId: '1:387756086923:web:b6f6550c674c9fd6c5268e',
    messagingSenderId: '387756086923',
    projectId: 'scoutapk',
    authDomain: 'scoutapk.firebaseapp.com',
    storageBucket: 'scoutapk.firebasestorage.app',
  );

}